# Generated by Django 3.0.14 on 2022-05-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spreadsheetui", "0005_auto_20200607_0957"),
    ]

    operations = [
        migrations.AlterField(
            model_name="torrentclient",
            name="client_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("deluge", "Deluge"),
                    ("rtorrent", "rtorrent"),
                    ("transmission", "Transmission"),
                    ("fakeclient", "FakeClient"),
                    ("qbittorrent", "qBittorrent"),
                    ("liltorrent", "LilTorrent"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
